name: ai-projects
channels:
  - pytorch
  - pyg
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg
  - numpy
  - pandas
  - matplotlib
  - notebook
  - ipykernel
  - onnx
  - onnxruntime
  - networkx
  - scipy
  - scikit-learn=1.3.0
  - pip:
    - torch-tensorrt
